### ISSUE TITLE
Typo in README.md - genicons.p ---> genicons.py

### ISSUE THREAD

**Issue by sp35** [creativecommons/licensebuttons#24]
## Describe the bug
Typo in README.md under Style/Syntax (Development Section)
```flake8 ./scripts/genicons.p```

https://github.com/creativecommons/licensebuttons/commit/23106301aaf4820239cc47f768190c24c6c9e1b9#r37563262

## Expected behavior
It should be changed to ```flake8 ./scripts/genicons.py```

**Comment by gabbyprecious** [comment]
Hello, is anyone working on this? Can I contribute to this?

**Comment by kgodey** [comment]
Go ahead @gabbyprecious

**Comment by gabbyprecious** [comment]
I have sent a pull request, please review and merge
